apiVersion: v1
kind: Service
metadata:
  name: core-api
  namespace: core-api
spec:
  type: LoadBalancer
  selector:
    app: core-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
